name: my_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  firebase_core: ^3.13.0   # Latest Firebase core version
  firebase_auth: ^5.5.2    # Latest Firebase Auth version
  firebase_auth_web: ^5.14.2  # Latest Firebase Web SDK version
  cupertino_icons: ^1.0.8
  provider: ^6.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
