// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc3BDShJK_EYYRl-SaF4_yHEHgoUHI6no',
    appId: '1:47356610726:android:b59ad14f8ff95bfd220c67',
    messagingSenderId: '47356610726',
    projectId: 'twitterclonetute-76b9b',
    storageBucket: 'twitterclonetute-76b9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcd_H-yFNcz3J1d6rnChiNLVuTe0YPDyk',
    appId: '1:47356610726:ios:62f4c01836145e1b220c67',
    messagingSenderId: '47356610726',
    projectId: 'twitterclonetute-76b9b',
    storageBucket: 'twitterclonetute-76b9b.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUUnSFsQ52qzELWGzhsaMpOQ-T2Hre-vE',
    appId: '1:47356610726:web:a8bbd67aa1330aa5220c67',
    messagingSenderId: '47356610726',
    projectId: 'twitterclonetute-76b9b',
    authDomain: 'twitterclonetute-76b9b.firebaseapp.com',
    storageBucket: 'twitterclonetute-76b9b.firebasestorage.app',
    measurementId: 'G-8F1RZRHG1K',
  );

}